In [169]:
import pandas as pd
import numpy as np

In [170]:
df = pd.read_csv("housing.csv")
df['income_cat'] = pd.cut(df['median_income'],bins=[0,1.5,3.0,4.5,6.0,np.inf],labels=[1,2,3,4,5]) #making another column for making bins

## Training & Testing Data

## Stratified Shuffle Split

In [173]:
#Making training and testing data to representative data of population

In [174]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(df,df['income_cat']):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [175]:
#that impressive sari income categories aa rahi he
#aisa nahi he all income catgory in training and not test(same vice versa)
#that why we use strata suffle

In [176]:
strat_train_set

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
12655      2237.0       706.0         2.1736             72100.0   
15502      2015.0       768.0         6.3373            279600.0   
2908        667.0       300.0         2.8750             82700.0   
14053       898.0       483.0         2.2264            112500.0   
20496      1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
15174      2026.0      1001.0         5.0900            268500.0   
12661      4769.0      1418.0         2.8139             90400.0   
19263       458.0       172.0         3.1797            140400.0   
19140      1208.0       501.0         4.1964            258100.0   
19773       625.0       197.0         3.1319             62700.0   

      ocean_proximity income_cat  
12655          INLAND          2  
15502      NEAR OCEAN          5  
2908           INLAND          2  
14053      NEAR OCEAN          2  
20496       <1H OCEAN          3  
...               ...        ...  
15174       <1H OCEAN          4  
12661          INLAND          2  
19263       <1H OCEAN          3  
19140       <1H OCEAN          3  
19773          INLAND          3  

[16512 rows x 11 columns]

In [177]:
strat_test_set

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
5241     -118.39     34.12                29.0       6447.0          1012.0   
17352    -120.42     34.89                24.0       2020.0           307.0   
3505     -118.45     34.25                36.0       1453.0           270.0   
7777     -118.10     33.91                35.0       1653.0           325.0   
14155    -117.07     32.77                38.0       3779.0           614.0   
...          ...       ...                 ...          ...             ...   
12182    -117.29     33.72                19.0       2248.0           427.0   
7275     -118.24     33.99                33.0        885.0           294.0   
17223    -119.72     34.44                43.0       1781.0           342.0   
10786    -117.91     33.63                30.0       2071.0           412.0   
3965     -118.56     34.19                36.0       2600.0           441.0   

       population  households  median_income  median_house_value  \
5241       2184.0       960.0         8.2816            500001.0   
17352       855.0       283.0         5.0099            162500.0   
3505        808.0       275.0         4.3839            204600.0   
7777       1072.0       301.0         3.2708            159700.0   
14155      1495.0       614.0         4.3529            184000.0   
...           ...         ...            ...                 ...   
12182      1207.0       368.0         2.8170            110000.0   
7275       1270.0       282.0         2.1615            118800.0   
17223       663.0       358.0         4.7000            293800.0   
10786      1081.0       412.0         4.9125            335700.0   
3965       1246.0       426.0         4.1111            215600.0   

      ocean_proximity income_cat  
5241        <1H OCEAN          5  
17352       <1H OCEAN          4  
3505        <1H OCEAN          3  
7777        <1H OCEAN          3  
14155      NEAR OCEAN          3  
...               ...        ...  
12182       <1H OCEAN          2  
7275        <1H OCEAN          2  
17223       <1H OCEAN          4  
10786       <1H OCEAN          4  
3965        <1H OCEAN          3  

[4128 rows x 11 columns]

In [178]:
# remove the income cat column
for sett in (strat_train_set,strat_test_set):
    sett.drop("income_cat",axis=1,inplace=True)

In [179]:
df = strat_train_set.copy()

In [180]:
df
strat_train_set

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
12655      2237.0       706.0         2.1736             72100.0   
15502      2015.0       768.0         6.3373            279600.0   
2908        667.0       300.0         2.8750             82700.0   
14053       898.0       483.0         2.2264            112500.0   
20496      1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
15174      2026.0      1001.0         5.0900            268500.0   
12661      4769.0      1418.0         2.8139             90400.0   
19263       458.0       172.0         3.1797            140400.0   
19140      1208.0       501.0         4.1964            258100.0   
19773       625.0       197.0         3.1319             62700.0   

      ocean_proximity  
12655          INLAND  
15502      NEAR OCEAN  
2908           INLAND  
14053      NEAR OCEAN  
20496       <1H OCEAN  
...               ...  
15174       <1H OCEAN  
12661          INLAND  
19263       <1H OCEAN  
19140       <1H OCEAN  
19773          INLAND  

[16512 rows x 10 columns]

In [181]:
#mistakly strat_train_set in median_house_value deleted so taking from df
housing_labels = df["median_house_value"].copy()
housing_labels

12655     72100.0
15502    279600.0
2908      82700.0
14053    112500.0
20496    238300.0
           ...   
15174    268500.0
12661     90400.0
19263    140400.0
19140    258100.0
19773     62700.0
Name: median_house_value, Length: 16512, dtype: float64

In [182]:
from sklearn.impute import SimpleImputer

In [183]:
imputer = SimpleImputer(strategy="median")#mean,most_frequent,most_frequent,constant

In [184]:
housing_num = df.select_dtypes(include=[np.number])

In [185]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [186]:
#imputer: ready to replace  missing value with median

In [187]:
imputer.statistics_

array([-1.18510e+02,  3.42600e+01,  2.90000e+01,  2.11900e+03,
        4.33000e+02,  1.16400e+03,  4.08000e+02,  3.54155e+00,
        1.79500e+05])

In [188]:
x = imputer.transform(housing_num)

In [189]:
x

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  7.0600e+02,
         2.1736e+00,  7.2100e+04],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  7.6800e+02,
         6.3373e+00,  2.7960e+05],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  3.0000e+02,
         2.8750e+00,  8.2700e+04],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  1.7200e+02,
         3.1797e+00,  1.4040e+05],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  5.0100e+02,
         4.1964e+00,  2.5810e+05],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  1.9700e+02,
         3.1319e+00,  6.2700e+04]])

In [190]:
housing = pd.DataFrame(x,columns=housing_num.columns,index=housing_num.index)
housing['ocean_proximity']=  df['ocean_proximity']
housing = housing[['ocean_proximity']]

In [191]:
print(set(housing['ocean_proximity']))
housing

{'NEAR BAY', 'NEAR OCEAN', '<1H OCEAN', 'ISLAND', 'INLAND'}


ocean_proximity
12655          INLAND
15502      NEAR OCEAN
2908           INLAND
14053      NEAR OCEAN
20496       <1H OCEAN
...               ...
15174       <1H OCEAN
12661          INLAND
19263       <1H OCEAN
19140       <1H OCEAN
19773          INLAND

[16512 rows x 1 columns]

## Ordianl Encoding

In [193]:
from sklearn.preprocessing import OrdinalEncoder


In [194]:
ordinal_encoder = OrdinalEncoder()
housing_cat = ordinal_encoder.fit_transform(housing)

In [195]:
housing_cat

array([[1.],
       [4.],
       [1.],
       ...,
       [0.],
       [0.],
       [1.]])

In [196]:
housing_cat = pd.DataFrame(housing_cat,columns=housing.columns,index=housing.index)
housing_cat

ocean_proximity
12655              1.0
15502              4.0
2908               1.0
14053              4.0
20496              0.0
...                ...
15174              0.0
12661              1.0
19263              0.0
19140              0.0
19773              1.0

[16512 rows x 1 columns]

## One Hot Encoding

In [198]:
from sklearn.preprocessing import OneHotEncoder

In [199]:
ordinal_encoder = OneHotEncoder()

In [200]:
housing_cat = ordinal_encoder.fit_transform(housing)
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [201]:
housing_cat.toarray()

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [202]:
# to back on dataframe

In [203]:
housing_cat = pd.DataFrame(housing_cat.toarray(),columns = ['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],index=housing.index)
housing_cat

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
12655        0.0     1.0     0.0       0.0         0.0
15502        0.0     0.0     0.0       0.0         1.0
2908         0.0     1.0     0.0       0.0         0.0
14053        0.0     0.0     0.0       0.0         1.0
20496        1.0     0.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
15174        1.0     0.0     0.0       0.0         0.0
12661        0.0     1.0     0.0       0.0         0.0
19263        1.0     0.0     0.0       0.0         0.0
19140        1.0     0.0     0.0       0.0         0.0
19773        0.0     1.0     0.0       0.0         0.0

[16512 rows x 5 columns]

In [204]:
df = pd.concat([df,housing_cat],axis=1)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  \
12655      2237.0       706.0         2.1736             72100.0   
15502      2015.0       768.0         6.3373            279600.0   
2908        667.0       300.0         2.8750             82700.0   
14053       898.0       483.0         2.2264            112500.0   
20496      1837.0       580.0         4.4964            238300.0   
...           ...         ...            ...                 ...   
15174      2026.0      1001.0         5.0900            268500.0   
12661      4769.0      1418.0         2.8139             90400.0   
19263       458.0       172.0         3.1797            140400.0   
19140      1208.0       501.0         4.1964            258100.0   
19773       625.0       197.0         3.1319             62700.0   

      ocean_proximity  <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN  
12655          INLAND        0.0     1.0     0.0       0.0         0.0  
15502      NEAR OCEAN        0.0     0.0     0.0       0.0         1.0  
2908           INLAND        0.0     1.0     0.0       0.0         0.0  
14053      NEAR OCEAN        0.0     0.0     0.0       0.0         1.0  
20496       <1H OCEAN        1.0     0.0     0.0       0.0         0.0  
...               ...        ...     ...     ...       ...         ...  
15174       <1H OCEAN        1.0     0.0     0.0       0.0         0.0  
12661          INLAND        0.0     1.0     0.0       0.0         0.0  
19263       <1H OCEAN        1.0     0.0     0.0       0.0         0.0  
19140       <1H OCEAN        1.0     0.0     0.0       0.0         0.0  
19773          INLAND        0.0     1.0     0.0       0.0         0.0  

[16512 rows x 15 columns]

In [205]:
df = df.drop("ocean_proximity",axis=1)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income  median_house_value  <1H OCEAN  \
12655      2237.0       706.0         2.1736             72100.0        0.0   
15502      2015.0       768.0         6.3373            279600.0        0.0   
2908        667.0       300.0         2.8750             82700.0        0.0   
14053       898.0       483.0         2.2264            112500.0        0.0   
20496      1837.0       580.0         4.4964            238300.0        1.0   
...           ...         ...            ...                 ...        ...   
15174      2026.0      1001.0         5.0900            268500.0        1.0   
12661      4769.0      1418.0         2.8139             90400.0        0.0   
19263       458.0       172.0         3.1797            140400.0        1.0   
19140      1208.0       501.0         4.1964            258100.0        1.0   
19773       625.0       197.0         3.1319             62700.0        0.0   

       INLAND  ISLAND  NEAR BAY  NEAR OCEAN  
12655     1.0     0.0       0.0         0.0  
15502     0.0     0.0       0.0         1.0  
2908      1.0     0.0       0.0         0.0  
14053     0.0     0.0       0.0         1.0  
20496     0.0     0.0       0.0         0.0  
...       ...     ...       ...         ...  
15174     0.0     0.0       0.0         0.0  
12661     1.0     0.0       0.0         0.0  
19263     0.0     0.0       0.0         0.0  
19140     0.0     0.0       0.0         0.0  
19773     1.0     0.0       0.0         0.0  

[16512 rows x 14 columns]

In [206]:
from sklearn.preprocessing import MinMaxScaler

In [207]:
scaler = MinMaxScaler(feature_range=(-1,1))
df_scaled = scaler.fit_transform(df)
df_scaled

array([[-0.42430279,  0.27098831,  0.09803922, ..., -1.        ,
        -1.        , -1.        ],
       [ 0.41832669, -0.88310308, -0.76470588, ..., -1.        ,
        -1.        ,  1.        ],
       [ 0.05776892, -0.39851222,  0.68627451, ..., -1.        ,
        -1.        , -1.        ],
       ...,
       [-0.6752988 ,  0.25398512,  0.84313725, ..., -1.        ,
        -1.        , -1.        ],
       [-0.67131474,  0.22635494, -0.49019608, ..., -1.        ,
        -1.        , -1.        ],
       [-0.55976096,  0.57917109,  0.01960784, ..., -1.        ,
        -1.        , -1.        ]])

In [208]:
# Doing Feature Scalling: Min & Max (Normalization) all values
df_scaled = pd.DataFrame(df_scaled,columns=df.columns,index=df.index)
df_scaled

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655  -0.424303  0.270988            0.098039    -0.803276       -0.743879   
15502   0.418327 -0.883103           -0.764706    -0.729664       -0.725193   
2908    0.057769 -0.398512            0.686275    -0.917994       -0.900773   
14053   0.438247 -0.955367           -0.098039    -0.904818       -0.833441   
20496   0.125498 -0.630181            0.019608    -0.820420       -0.792526   
...          ...       ...                 ...          ...             ...   
15174   0.450199 -0.895855           -0.490196    -0.661240       -0.604059   
12661  -0.416335  0.268863           -0.450980    -0.598362       -0.542526   
19263  -0.675299  0.253985            0.843137    -0.964338       -0.947165   
19140  -0.671315  0.226355           -0.490196    -0.839803       -0.813789   
19773  -0.559761  0.579171            0.019608    -0.945414       -0.929124   

       population  households  median_income  median_house_value  <1H OCEAN  \
12655   -0.874772   -0.737117      -0.769148           -0.764533       -1.0   
15502   -0.887217   -0.713966      -0.194852            0.091134       -1.0   
2908    -0.962779   -0.888723      -0.672405           -0.720822       -1.0   
14053   -0.949830   -0.820388      -0.761865           -0.597936       -1.0   
20496   -0.897194   -0.784167      -0.448766           -0.079175        1.0   
...           ...         ...            ...                 ...        ...   
15174   -0.886600   -0.626960      -0.366891            0.045361        1.0   
12661   -0.732840   -0.471247      -0.680832           -0.689069       -1.0   
19263   -0.974495   -0.936520      -0.630378           -0.482885        1.0   
19140   -0.932453   -0.813667      -0.490145            0.002474        1.0   
19773   -0.965134   -0.927184      -0.636971           -0.803296       -1.0   

       INLAND  ISLAND  NEAR BAY  NEAR OCEAN  
12655     1.0    -1.0      -1.0        -1.0  
15502    -1.0    -1.0      -1.0         1.0  
2908      1.0    -1.0      -1.0        -1.0  
14053    -1.0    -1.0      -1.0         1.0  
20496    -1.0    -1.0      -1.0        -1.0  
...       ...     ...       ...         ...  
15174    -1.0    -1.0      -1.0        -1.0  
12661     1.0    -1.0      -1.0        -1.0  
19263    -1.0    -1.0      -1.0        -1.0  
19140    -1.0    -1.0      -1.0        -1.0  
19773     1.0    -1.0      -1.0        -1.0  

[16512 rows x 14 columns]

In [209]:
## if you think data in can be outiners and wrong keys & data so Noramlization is not recommended

In [210]:
## use Standardization(Z-Score Scalling)

In [211]:
from sklearn.preprocessing import StandardScaler

In [212]:
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)
df_scaled = pd.DataFrame(df_scaled,columns = df.columns,index = df.index)
df_scaled

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655  -0.941350  1.347438            0.027564     0.584777        0.635123   
15502   1.171782 -1.192440           -1.722018     1.261467        0.775677   
2908    0.267581 -0.125972            1.220460    -0.469773       -0.545045   
14053   1.221738 -1.351474           -0.370069    -0.348652       -0.038567   
20496   0.437431 -0.635818           -0.131489     0.427179        0.269198   
...          ...       ...                 ...          ...             ...   
15174   1.251711 -1.220505           -1.165333     1.890456        1.686854   
12661  -0.921368  1.342761           -1.085806     2.468471        2.149712   
19263  -1.570794  1.310018            1.538566    -0.895802       -0.894007   
19140  -1.560803  1.249211           -1.165333     0.249005        0.109257   
19773  -1.281050  2.025674           -0.131489    -0.721836       -0.758300   

       population  households  median_income  median_house_value  <1H OCEAN  \
12655    0.732602    0.556286      -0.893647           -1.166015  -0.887683   
15502    0.533612    0.721318       1.292168            0.627451  -0.887683   
2908    -0.674675   -0.524407      -0.525434           -1.074397  -0.887683   
14053   -0.467617   -0.037297      -0.865929           -0.816829  -0.887683   
20496    0.374060    0.220898       0.325752            0.270486   1.126529   
...           ...         ...            ...                 ...        ...   
15174    0.543471    1.341519       0.637374            0.531511   1.126529   
12661    3.002174    2.451492      -0.557509           -1.007844  -0.887683   
19263   -0.862013   -0.865118      -0.365475           -0.575684   1.126529   
19140   -0.189747    0.010616       0.168261            0.441622   1.126529   
19773   -0.712322   -0.798573      -0.390569           -1.247261  -0.887683   

        INLAND    ISLAND  NEAR BAY  NEAR OCEAN  
12655  1.46218 -0.011006 -0.354889   -0.384217  
15502 -0.68391 -0.011006 -0.354889    2.602693  
2908   1.46218 -0.011006 -0.354889   -0.384217  
14053 -0.68391 -0.011006 -0.354889    2.602693  
20496 -0.68391 -0.011006 -0.354889   -0.384217  
...        ...       ...       ...         ...  
15174 -0.68391 -0.011006 -0.354889   -0.384217  
12661  1.46218 -0.011006 -0.354889   -0.384217  
19263 -0.68391 -0.011006 -0.354889   -0.384217  
19140 -0.68391 -0.011006 -0.354889   -0.384217  
19773  1.46218 -0.011006 -0.354889   -0.384217  

[16512 rows x 14 columns]

In [ ]:
#most of data points around mean point

#recommended for gradient scaling